<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.iwantjob</groupId>
        <artifactId>iwantjob-backend</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>iwantjob-api</artifactId>
    <name>iwantjob-api</name>
    <description>聚合启动模块</description>

    <dependencies>
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-ai</artifactId>
        </dependency>
        <!-- 第一阶段业务模块 -->
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-user</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- 第二阶段业务模块 -->
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-job</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-resume</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-interview</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-salary</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-simulator</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-badge</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-community</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iwantjob</groupId>
            <artifactId>iwantjob-helpgroup</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
